FROM ubuntu:20.04
MAINTAINER jwang
USER root

# Install OpenJDK-8
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y net-tools && \
    apt-get install -y telnetd && \
    apt-get install -y dnsutils && \
    apt-get install -y iputils-ping &&\
    apt-get install -y vim && \
    apt-get install -y ant;

# Fix certificate issues
RUN apt-get install ca-certificates-java && \
    update-ca-certificates -f;

# install wget gpg
RUN apt-get install -y wget && \
    apt-get install -y gnupg && \
    apt-get clean;

# set up env vars
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-arm64/
ENV ZOOKEEPER_VERSION 3.5.8
ENV ZOOKEEPER_HOME /opt/zookeeper
ENV KAFKA_VERSION=2.6.0 \
    SCALA_VERSION=2.13
ENV PATH=${PATH}:${ZOOKEEPER_HOME}/bin


# copy a kafka binary release
ADD kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/zookeeper
RUN mkdir /var/lib/zookeeper /var/lib/zookeeper/data /var/lib/zookeeper/log

EXPOSE 2181 2888 3888
WORKDIR /opt/zookeeper

# entry point
ADD start_zookeeper.sh /usr/bin/start_zookeeper.sh
ENTRYPOINT ["start_zookeeper.sh"]
