4lw.commands.whitelist=ruok
clientPort=2181
dataDir=/var/lib/zookeeper/data
dataLogDir=/var/lib/zookeeper/log
tickTime=2000
initLimit=10
syncLimit=2000
maxClientCnxns=60
minSessionTimeout=4000
maxSessionTimeout=40000
autopurge.snapRetainCount=3
autopurge.purgeInterval=0
tcpKeepAlive=true
electionPortBindRetry=0
servers=3
server.1=kafka-zookeeper-0.kafka-zookeeper-headless.dev.svc.cluster.local:2888:3888:participant
server.2=kafka-zookeeper-1.kafka-zookeeper-headless.dev.svc.cluster.local:2888:3888:participant
server.3=kafka-zookeeper-2.kafka-zookeeper-headless.dev.svc.cluster.local:2888:3888:participant
