4lw.commands.whitelist=ruok
clientPort=2181
dataDir=/var/lib/zookeeper/data
dataLogDir=/var/lib/zookeeper/log
tickTime=2000
initLimit=10
syncLimit=2000
maxClientCnxns=60
minSessionTimeout=4000
maxSessionTimeout=40000
tcpKeepAlive=true
electionPortBindRetry=0
servers=1
server.1=zookeeper-0.zookeeper-headless.kafka.svc.microk8s-cluster.local:2888:3888:participant
